version: 2
jobs:
  build:
    environment:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"
      _JAVA_OPTIONS: -Xms512m -Xmx1024m
    docker:
      - image: circleci/android:api-28

    steps:
    - checkout
    - restore_cache:
        keys:
        - dep-{{ checksum "./app/build.gradle" }}
        - dep-
    - run: ./gradlew clean build
    - save_cache:
        key: dep-{{ checksum "./app/build.gradle" }}
        paths:
        - ~/.gradle
        - ~/.android
        - /usr/local/android-sdk-linux/extras
    - run: ./gradlew test jacocoTestReport --continue --console=plain
    - run:
          name: Upload Coverage
          when: on_success
          command: bash <(curl -s https://codecov.io/bash) -Z -C $CIRCLE_SHA1